# Generated by Django 5.0.3 on 2024-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
